on:
  push:
    branches:
      - main
    paths:
      - create_pr_test/**

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'test-branch-${{ github.run_id }}'
