on:
  push:
    branches:
      - main
    paths:
      - create_pr_test/**

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: create branch
        uses: actions/checkout@v3
        with:
          ref: 'test-branch-${{ github.run_id }}'
