on:
  push:
    branches:
      - main
    paths:
      - create_pr_test/**

env:
  BRANCH_NAME: 'test-branch-${{ github.run_id }}'

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.BRANCH_NAME }}
  terraform-docs:
    runs-on: ubuntu-latest
    needs: [create_branch]
    steps:
      - name: checkout to branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
      - name: Rendering terraform docs and push
        uses: terraform-docs/gh-actions@main
        with:
          find-dir: modules/
          recursive: true
          recursive-path: .
          output-method: replace
          git-push: "true"
          template: |-
            {{ .Content }}
            # Test Terraform docs

            ## Verify

            Should use the template defined instead of the default
            Should inject the table under usage
      - name: Create Pull Request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ env.BRANCH_NAME }}
          destination_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 'TEST AUTO PR'
          pr_body: |
            테스트용 PR
            - test1
            - test2
      - name: output-url
        run: echo ${{steps.open-pr.outputs.pr_url}}
      - name: output-number
        run: echo ${{steps.open-pr.outputs.pr_number}}
      - name: output-has-changed-files
        run: echo ${{steps.open-pr.outputs.has_changed_files}}
