on:
  workflow_run:
    workflows: [Test Action]
    types:
      - completed

jobs:
  docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout the codes
        uses: actions/checkout@v2
      - name: Rendering terraform docs and push
        uses: terraform-docs/gh-actions@main
        with:
          find-dir: modules/
          recursive: true
          recursive-path: .
          output-method: replace
          git-push: "true"
          template: |-
            # Test Terraform docs

            ## Verify

            Should use the template defined instead of the default
            Should inject the table under usage

            {{ .Content }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure }}
    steps:
      - run: echo 'Fail'
