on:
  pull_request:
    paths:
      - modules/**

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Rendering terraform docs and push
        uses: terraform-docs/gh-actions@main
        with:
          find-dir: modules/
          recursive: true
          recursive-path: .
          output-method: replace
          git-push: "true"
          template: |-
            # Test Terraform docs

            ## Verify

            Should use the template defined instead of the default
            Should inject the table under usage

            {{ .Content }}
